### ISSUE TITLE
Is there any plan to add support for username password?

### ISSUE THREAD

**Issue by nitinpawar** [yc-huang/Hive-mongo#13]
Hi,

is there any plan to add username password to connection strings? If it is already not there

I tried to locate but could not find

**Comment by yc-huang** [comment]
currently it's not supported, but it won't cost much to support that...

might add this feature next week if I'm free.

**Comment by nitinpawar** [comment]
I will try to implement it. 
I have not used java before but will give it a shot. :)

**Comment by yc-huang** [comment]
I've submit fix for this, would you have a try? you might find the ootb jar file (hive-mongo-0.0.3-jar-with-dependencies) under "release" directory without need to build from source.

**Comment by nitinpawar** [comment]
Will give it a try tomorrow. Today is a holiday for us

On Mon, Sep 9, 2013 at 12:57 PM, yc-huang notifications@github.com wrote:

> I've submit fix for this, would you have a try? you might find the ootb
> jar file (hive-mongo-0.0.3-jar-with-dependencies) under "release" directory
> without need to build from source.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/yc-huang/Hive-mongo/issues/13#issuecomment-24049560
> .

## 

Nitin Pawar

**Comment by brianchizhang** [comment]
Fantastic fix, thank you Huang!
